name: Publish to DockerHub
on:
  push:
    branches: [ master, "feature/#86-quarkus" ]
    paths:
      - 'src/**'
      - 'build.gradle'
      - '.github/workflows/publish.yml'
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Publish
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build and publish
        run: ./gradlew build -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true
        env:
          QUARKUS_CONTAINER_IMAGE_GROUP: akop
          QUARKUS_CONTAINER_IMAGE_NAME: home-system
          QUARKUS_CONTAINER_IMAGE_TAG: latest
          QUARKUS_CONTAINER_IMAGE_USERNAME: '${{ secrets.DOCKER_USER }}'
          QUARKUS_CONTAINER_IMAGE_PASSWORD: '${{ secrets.DOCKER_PASS }}'
          REPO_USERNAME: '${{ secrets.REPO_GITHUB_NAME }}'
          REPO_TOKEN: '${{ secrets.REPO_GITHUB_TOKEN }}'
